#!/usr/bin/env python3
"""
TCGA COAD/READ survival analysis
- Generates TCGA-based survival figures (OS and PFI Kaplan–Meier plots) and summary tables from `tcga_analysis_table.csv`.


INPUT
-----
Default expects:
  results/processed/tcga_analysis_table.csv
  (generated by tcga_analysis.py)

  
OUTPUTS
-------
  (1) OS and PFI Kaplan–Meier plots (5-year cutoff, stage-stratified)
     - CD24 High vs Low (median split)
  (2) Stage-stratified survival CSV tables (OS + PFI)
     - CHR via Cox model + log-rank p-value
  (3) Clinical characteristics table

Written to:
  results/figures_tables/
  - CD24_OS_PFI.png
  - AllPatients_ClinicalCharacteristics.png
  - AllPatients_ClinicalCharacteristics.csv
  - Stage-stratified OS and PFI summary CSV files

"""

from __future__ import annotations
import argparse
import re
import warnings
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from matplotlib.patches import Rectangle as Rect
from lifelines import KaplanMeierFitter, CoxPHFitter
from lifelines.statistics import logrank_test
from lifelines.utils import ConvergenceWarning


# -----------------------------
# Defaults
# -----------------------------
SAVE_FIGURES = True
FIGURE_FORMAT = "png"
DPI = 300


# -----------------------------
# Helpers: CD24 High/Low
# -----------------------------
def analyze_cd24_stage_highlow_5yr(
    stage_data: pd.DataFrame,
    stage_name: str,
    endpoint: str = "OS",
):
    """
    Analyze CD24 survival for high vs low (median split), truncate at 5 years (60 months).

    Returns:
      groups_data (dict[str, DataFrame]),
      result (lifelines logrank result with extra attrs),
      has_sufficient_events (bool),
      group_stats (dict[str, dict])
    """
    if endpoint == "OS":
        time_col, event_col = "time", "event"
    elif endpoint == "PFI":
        time_col, event_col = "pfi_time", "pfi_event"
    else:
        raise ValueError(f"Unknown endpoint: {endpoint}")

    if time_col not in stage_data.columns or event_col not in stage_data.columns:
        return None, None, False, None

    stage_data = stage_data.dropna(subset=[time_col, event_col, "CD24_expr"]).copy()
    if len(stage_data) < 20:
        return None, None, False, None

    # Censor at 5 years (60 months)
    stage_data[f"{time_col}_5yr"] = pd.to_numeric(stage_data[time_col], errors="coerce").clip(upper=60)
    stage_data[f"{event_col}_5yr"] = stage_data.apply(
        lambda row: 0 if row[time_col] > 60 else row[event_col], axis=1
    )

    cd24_median = stage_data["CD24_expr"].median()
    stage_data["CD24_group"] = stage_data["CD24_expr"].apply(lambda x: "High" if x >= cd24_median else "Low")

    groups_data = {
        "Low": stage_data[stage_data["CD24_group"] == "Low"].copy(),
        "High": stage_data[stage_data["CD24_group"] == "High"].copy(),
    }

    total_events = 0
    group_stats = {}
    for group in ["Low", "High"]:
        n = len(groups_data[group])
        events = int(pd.to_numeric(groups_data[group][f"{event_col}_5yr"], errors="coerce").sum())
        total_events += events
        group_stats[group] = {
            "n": n,
            "events": events,
            "censored": n - events,
            "event_rate": (events / n * 100) if n > 0 else 0,
        }

    has_sufficient_events = total_events >= 5
    if not has_sufficient_events:
        return groups_data, None, False, group_stats

    result = logrank_test(
        groups_data["Low"][f"{time_col}_5yr"],
        groups_data["High"][f"{time_col}_5yr"],
        groups_data["Low"][f"{event_col}_5yr"],
        groups_data["High"][f"{event_col}_5yr"],
    )

    # Cox model HR (univariate)
    try:
        cox_data = stage_data[[f"{time_col}_5yr", f"{event_col}_5yr", "CD24_group"]].copy()
        cox_data["CD24_High"] = (cox_data["CD24_group"] == "High").astype(int)
        cox_data = cox_data.drop(columns=["CD24_group"])

        cph = CoxPHFitter()
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", category=ConvergenceWarning)
            warnings.simplefilter("ignore", category=RuntimeWarning)
            cph.fit(cox_data, duration_col=f"{time_col}_5yr", event_col=f"{event_col}_5yr")

        hr = float(np.exp(cph.params_["CD24_High"]))
        ci = np.exp(cph.confidence_intervals_.loc["CD24_High"])
        p_hr = float(cph.summary.loc["CD24_High", "p"])
        result.hr = (hr, float(ci.iloc[0]), float(ci.iloc[1]), p_hr)
    except Exception:
        result.hr = None

    result.time_col = f"{time_col}_5yr"
    result.event_col = f"{event_col}_5yr"
    return groups_data, result, True, group_stats


def plot_highlow_survival_5yr(ax, groups_data, result, stage_name: str, endpoint: str = "OS"):
    endpoint_labels = {"OS": "Overall survival", "PFI": "Progression-free survival"}

    if result is None or groups_data is None:
        ax.text(
            0.5,
            0.5,
            f"{stage_name}\nInsufficient data",
            ha="center",
            va="center",
            fontsize=14,
            transform=ax.transAxes,
        )
        ax.set_xlim([0, 60])
        ax.set_ylim([0, 105])
        ax.set_xlabel("Time (months)")
        ax.set_ylabel(f"{endpoint_labels[endpoint]} (%)")
        ax.set_title(stage_name, fontsize=13, fontweight="bold")
        ax.grid(True, alpha=0.3)
        return

    time_col = result.time_col
    event_col = result.event_col

    colors = {"Low": "#1E88E5", "High": "#E53935"}
    kmf = KaplanMeierFitter()

    for group in ["Low", "High"]:
        data = groups_data[group]
        kmf.fit(data[time_col], data[event_col])

        sf = kmf.survival_function_
        times = sf.index.values
        surv_probs_pct = sf.iloc[:, 0].values * 100

        ci = kmf.confidence_interval_survival_function_
        ci_lower_pct = ci.iloc[:, 0].values * 100
        ci_upper_pct = ci.iloc[:, 1].values * 100

        ax.fill_between(times, ci_lower_pct, ci_upper_pct, color=colors[group], alpha=0.15, step="post", linewidth=0)
        ax.step(times, surv_probs_pct, where="post", color=colors[group], linewidth=2.5, label=group)

    ax.set_ylim([0, 105])
    ax.set_xlim([0, 60])
    ax.xaxis.set_major_locator(ticker.MultipleLocator(12))
    ax.yaxis.set_major_locator(ticker.MultipleLocator(20))
    ax.set_xlabel("Time (months)", fontsize=12, fontweight="bold")
    ax.set_ylabel(f"{endpoint_labels[endpoint]} (%)", fontsize=12, fontweight="bold")
    ax.set_title(f"{stage_name}", fontsize=13, fontweight="bold", pad=10)
    ax.grid(True, alpha=0.3)

    # Show p-value on plot
    pval = getattr(result, "p_value", np.nan)
    if np.isfinite(pval):
        is_significant = pval < 0.05
        edge_color = "#FF9800" if is_significant else "#BDBDBD"
        edge_width = 2.5 if is_significant else 1.5
        text = f"p={pval:.4f}"
        ax.text(
            0.97,
            0.03,
            text,
            transform=ax.transAxes,
            fontsize=10,
            fontweight="normal",
            va="bottom",
            ha="right",
            bbox=dict(boxstyle="round", facecolor="#E0E0E0", alpha=0.7, edgecolor=edge_color, linewidth=edge_width),
            color="black",
        )


def create_combined_os_pfi_figure(results_os, results_pfi, out_path: Path):
    fig, axes = plt.subplots(2, 4, figsize=(20, 10))
    stages = ["Stage I", "Stage II", "Stage III", "Stage IV"]

    for idx, stage in enumerate(stages):
        ax = axes[0, idx]
        if stage in results_os and results_os[stage]["sufficient"]:
            plot_highlow_survival_5yr(ax, results_os[stage]["groups"], results_os[stage]["result"], stage, "OS")
            if idx == 0:
                legend = ax.legend(
                    loc="lower left",
                    fontsize=11,
                    frameon=True,
                    title="CD24 expression",
                    title_fontsize=11,
                    framealpha=0.95,
                    edgecolor="black",
                )
                legend.get_title().set_fontweight("bold")
        else:
            plot_highlow_survival_5yr(ax, None, None, stage, "OS")

    for idx, stage in enumerate(stages):
        ax = axes[1, idx]
        if stage in results_pfi and results_pfi[stage]["sufficient"]:
            plot_highlow_survival_5yr(ax, results_pfi[stage]["groups"], results_pfi[stage]["result"], stage, "PFI")
            if idx == 0:
                legend = ax.legend(
                    loc="lower left",
                    fontsize=11,
                    frameon=True,
                    title="CD24 expression",
                    title_fontsize=11,
                    framealpha=0.95,
                    edgecolor="black",
                )
                legend.get_title().set_fontweight("bold")
        else:
            plot_highlow_survival_5yr(ax, None, None, stage, "PFI")

    plt.subplots_adjust(left=0.05, right=0.98, top=0.95, bottom=0.08, hspace=0.3, wspace=0.25)
    if SAVE_FIGURES:
        fig.savefig(out_path, dpi=DPI, bbox_inches="tight")
    plt.close(fig)


# -----------------------------
# Clinical characteristics table
# -----------------------------
def calculate_characteristics(data: pd.DataFrame) -> dict:
    """
    Compute clinical characteristics for the clinical table.

    """
    chars: dict[str, object] = {"N": int(len(data))}

    def _norm_series(s: pd.Series) -> pd.Series:
        return s.astype(str).str.strip().str.lower().replace({"nan": np.nan, "none": np.nan, "": np.nan})

    # Cancer type
    if "cancer_type" in data.columns:
        ct = _norm_series(data["cancer_type"])
        type_counts = ct.value_counts(dropna=True)
        chars["COAD_n"] = int(type_counts.get("coad", 0))
        chars["READ_n"] = int(type_counts.get("read", 0))
        chars["COAD_pct"] = (chars["COAD_n"] / len(data) * 100) if len(data) else 0
        chars["READ_pct"] = (chars["READ_n"] / len(data) * 100) if len(data) else 0

    # Age
    if "age_at_diagnosis" in data.columns:
        age = pd.to_numeric(data["age_at_diagnosis"], errors="coerce").dropna()
        if len(age):
            chars["Age_median"] = float(age.median())
            chars["Age_range"] = f"{age.min():.0f}-{age.max():.0f}"

    # Sex
    if "gender" in data.columns:
        sex = _norm_series(data["gender"])
        sex_counts = sex.value_counts(dropna=True)
        chars["Male_n"] = int(sex_counts.get("male", 0))
        chars["Female_n"] = int(sex_counts.get("female", 0))
        chars["Male_pct"] = (chars["Male_n"] / len(data) * 100) if len(data) else 0
        chars["Female_pct"] = (chars["Female_n"] / len(data) * 100) if len(data) else 0

    # Race
    if "race" in data.columns:
        race_series = (
            data["race"]
            .astype(str)
            .str.strip()
            .str.upper()
            .replace({"": np.nan, "NAN": np.nan})
        )

        race_map = {
            "WHITE": "White",
            "BLACK OR AFRICAN AMERICAN": "Black/African American",
            "ASIAN": "Asian",
            "AMERICAN INDIAN OR ALASKA NATIVE": "American Indian/Alaska Native",
        }

        known_mask = race_series.isin(race_map.keys())
        known = race_series[known_mask].map(race_map)

        race_counts = known.value_counts()

        for label in race_map.values():
            n = int(race_counts.get(label, 0))
            pct = (n / len(data) * 100) if len(data) else 0
            key = label.lower().replace("/", "_").replace(" ", "_")
            chars[f"Race_{key}_n"] = n
            chars[f"Race_{key}_pct"] = pct

        unknown_n = int((~known_mask).sum())
        chars["Race_not_reported_n"] = unknown_n
        chars["Race_not_reported_pct"] = (unknown_n / len(data) * 100) if len(data) else 0

    # Vital status
    if "vital_status" in data.columns:
        vital = _norm_series(data["vital_status"])
        vital_counts = vital.value_counts(dropna=True)
        chars["Alive_n"] = int(vital_counts.get("alive", 0))
        chars["Dead_n"] = int(vital_counts.get("dead", 0) + vital_counts.get("deceased", 0))
        chars["Alive_pct"] = (chars["Alive_n"] / len(data) * 100) if len(data) else 0
        chars["Dead_pct"] = (chars["Dead_n"] / len(data) * 100) if len(data) else 0

    # Stage
    if "stage" in data.columns:
        st = _norm_series(data["stage"]).str.replace("stage ", "", regex=False)
        for s in ["i", "ii", "iii", "iv"]:
            n = int((st == s).sum())
            pct = (n / len(data) * 100) if len(data) else 0
            chars[f"Stage_{s.upper()}_n"] = n
            chars[f"Stage_{s.upper()}_pct"] = pct

    # OS
    if "time" in data.columns and "event" in data.columns:
        osd = data[["time", "event"]].copy()
        osd["time"] = pd.to_numeric(osd["time"], errors="coerce")
        osd["event"] = pd.to_numeric(osd["event"], errors="coerce")
        osd = osd.dropna()
        if len(osd):
            chars["OS_median_months"] = float(osd["time"].median())
            chars["OS_events"] = float(osd["event"].sum())
            chars["OS_event_rate"] = (chars["OS_events"] / len(osd) * 100) if len(osd) else 0

    # PFI
    if "pfi_time" in data.columns and "pfi_event" in data.columns:
        pfid = data[["pfi_time", "pfi_event"]].copy()
        pfid["pfi_time"] = pd.to_numeric(pfid["pfi_time"], errors="coerce")
        pfid["pfi_event"] = pd.to_numeric(pfid["pfi_event"], errors="coerce")
        pfid = pfid.dropna()
        if len(pfid):
            chars["PFI_median_months"] = float(pfid["pfi_time"].median())
            chars["PFI_events"] = float(pfid["pfi_event"].sum())
            chars["PFI_event_rate"] = (chars["PFI_events"] / len(pfid) * 100) if len(pfid) else 0

    return chars


def build_and_save_clin_table_figure(df: pd.DataFrame, fig_path: Path, csv_path: Path):
    overall_stats = calculate_characteristics(df)
    cd24_low_stats = calculate_characteristics(df[df["CD24_binary"] == "Low"]) if "CD24_binary" in df.columns else {}
    cd24_high_stats = calculate_characteristics(df[df["CD24_binary"] == "High"]) if "CD24_binary" in df.columns else {}

    table_rows = []

    def add_row(label, overall, low, high):
        table_rows.append([label, overall, low, high])

    add_row("N", str(overall_stats["N"]), str(cd24_low_stats.get("N", "")), str(cd24_high_stats.get("N", "")))

    if "Age_median" in overall_stats:
        add_row(
            "Age, median (range), years",
            f'{overall_stats["Age_median"]:.1f} ({overall_stats["Age_range"]})',
            f'{cd24_low_stats.get("Age_median", np.nan):.1f} ({cd24_low_stats.get("Age_range", "")})'
            if "Age_median" in cd24_low_stats
            else "",
            f'{cd24_high_stats.get("Age_median", np.nan):.1f} ({cd24_high_stats.get("Age_range", "")})'
            if "Age_median" in cd24_high_stats
            else "",
        )

    add_row("Cancer type, n (%)", "", "", "")
    if "COAD_n" in overall_stats:
        add_row(
            "  Colon (COAD)",
            f'{overall_stats["COAD_n"]} ({overall_stats["COAD_pct"]:.1f})',
            f'{cd24_low_stats.get("COAD_n", 0)} ({cd24_low_stats.get("COAD_pct", 0):.1f})',
            f'{cd24_high_stats.get("COAD_n", 0)} ({cd24_high_stats.get("COAD_pct", 0):.1f})',
        )
        add_row(
            "  Rectal (READ)",
            f'{overall_stats["READ_n"]} ({overall_stats["READ_pct"]:.1f})',
            f'{cd24_low_stats.get("READ_n", 0)} ({cd24_low_stats.get("READ_pct", 0):.1f})',
            f'{cd24_high_stats.get("READ_n", 0)} ({cd24_high_stats.get("READ_pct", 0):.1f})',
        )

    add_row("Sex, n (%)", "", "", "")
    if "Male_n" in overall_stats:
        add_row(
            "  Male",
            f'{overall_stats["Male_n"]} ({overall_stats["Male_pct"]:.1f})',
            f'{cd24_low_stats.get("Male_n", 0)} ({cd24_low_stats.get("Male_pct", 0):.1f})',
            f'{cd24_high_stats.get("Male_n", 0)} ({cd24_high_stats.get("Male_pct", 0):.1f})',
        )
        add_row(
            "  Female",
            f'{overall_stats["Female_n"]} ({overall_stats["Female_pct"]:.1f})',
            f'{cd24_low_stats.get("Female_n", 0)} ({cd24_low_stats.get("Female_pct", 0):.1f})',
            f'{cd24_high_stats.get("Female_n", 0)} ({cd24_high_stats.get("Female_pct", 0):.1f})',
        )

        add_row("Race, n (%)", "", "", "")

        for race, label in [
            ("white", "White"),
            ("black_african_american", "Black/African American"),
            ("asian", "Asian"),
            ("american_indian_alaska_native", "American Indian/Alaska Native"),
            ("not_reported", "Not reported"),
        ]:
            key = f"Race_{race}_n"
            if key in overall_stats:
                add_row(
                    f"  {label}",
                    f'{overall_stats[key]} ({overall_stats[f"Race_{race}_pct"]:.1f})',
                    f'{cd24_low_stats.get(key, 0)} ({cd24_low_stats.get(f"Race_{race}_pct", 0):.1f})',
                    f'{cd24_high_stats.get(key, 0)} ({cd24_high_stats.get(f"Race_{race}_pct", 0):.1f})'
                )

    add_row("Stage, n (%)", "", "", "")
    if "Stage_I_n" in overall_stats:
        for st in ["I", "II", "III", "IV"]:
            add_row(
                f"  Stage {st}",
                f'{overall_stats[f"Stage_{st}_n"]} ({overall_stats[f"Stage_{st}_pct"]:.1f})',
                f'{cd24_low_stats.get(f"Stage_{st}_n", 0)} ({cd24_low_stats.get(f"Stage_{st}_pct", 0):.1f})',
                f'{cd24_high_stats.get(f"Stage_{st}_n", 0)} ({cd24_high_stats.get(f"Stage_{st}_pct", 0):.1f})',
            )

    add_row("Vital status, n (%)", "", "", "")
    if "Alive_n" in overall_stats:
        add_row(
            "  Alive",
            f'{overall_stats["Alive_n"]} ({overall_stats["Alive_pct"]:.1f})',
            f'{cd24_low_stats.get("Alive_n", 0)} ({cd24_low_stats.get("Alive_pct", 0):.1f})',
            f'{cd24_high_stats.get("Alive_n", 0)} ({cd24_high_stats.get("Alive_pct", 0):.1f})',
        )
        add_row(
            "  Deceased",
            f'{overall_stats["Dead_n"]} ({overall_stats["Dead_pct"]:.1f})',
            f'{cd24_low_stats.get("Dead_n", 0)} ({cd24_low_stats.get("Dead_pct", 0):.1f})',
            f'{cd24_high_stats.get("Dead_n", 0)} ({cd24_high_stats.get("Dead_pct", 0):.1f})',
        )

    add_row("Overall Survival", "", "", "")
    if "OS_median_months" in overall_stats:
        add_row(
            "  Median follow-up, months",
            f'{overall_stats["OS_median_months"]:.1f}',
            f'{cd24_low_stats.get("OS_median_months", np.nan):.1f}' if "OS_median_months" in cd24_low_stats else "",
            f'{cd24_high_stats.get("OS_median_months", np.nan):.1f}' if "OS_median_months" in cd24_high_stats else "",
        )
        add_row(
            "  Events, n (%)",
            f'{int(overall_stats["OS_events"])} ({overall_stats["OS_event_rate"]:.1f})',
            f'{int(cd24_low_stats.get("OS_events", 0))} ({cd24_low_stats.get("OS_event_rate", 0):.1f})',
            f'{int(cd24_high_stats.get("OS_events", 0))} ({cd24_high_stats.get("OS_event_rate", 0):.1f})',
        )

    add_row("Progression-Free Interval", "", "", "")
    if "PFI_median_months" in overall_stats:
        add_row(
            "  Median follow-up, months",
            f'{overall_stats["PFI_median_months"]:.1f}',
            f'{cd24_low_stats.get("PFI_median_months", np.nan):.1f}' if "PFI_median_months" in cd24_low_stats else "",
            f'{cd24_high_stats.get("PFI_median_months", np.nan):.1f}' if "PFI_median_months" in cd24_high_stats else "",
        )
        add_row(
            "  Events, n (%)",
            f'{int(overall_stats["PFI_events"])} ({overall_stats["PFI_event_rate"]:.1f})',
            f'{int(cd24_low_stats.get("PFI_events", 0))} ({cd24_low_stats.get("PFI_event_rate", 0):.1f})',
            f'{int(cd24_high_stats.get("PFI_events", 0))} ({cd24_high_stats.get("PFI_event_rate", 0):.1f})',
        )

    # Save CSV
    header = ["Characteristic", "All Patients", "CD24 Low", "CD24 High"]
    pd.DataFrame(table_rows, columns=header).to_csv(csv_path, index=False)

    # Draw figure (keep your style)
    fig_width = 10.5
    fig_height = len(table_rows) * 0.33 + 2.2
    fig, ax = plt.subplots(figsize=(fig_width, fig_height))
    ax.axis("tight")
    ax.axis("off")

    col_widths = [0.20, 0.10, 0.10, 0.10]
    table_bbox = [0.01, 0, 0.98, 0.87]
    table = ax.table(cellText=table_rows, cellLoc="left", loc="center", bbox=table_bbox)
    table.auto_set_font_size(False)
    table.set_fontsize(14)
    table.scale(1, 2.4)

    for i, width in enumerate(col_widths):
        for r in range(len(table_rows)):
            table[(r, i)].set_width(width)

    table_left, table_width = table_bbox[0], table_bbox[2]
    total_width = sum(col_widths)
    col_boundaries = [table_left]
    for width in col_widths:
        col_boundaries.append(col_boundaries[-1] + (width / total_width) * table_width)

    def get_scaled_width(idx):
        return col_boundaries[idx + 1] - col_boundaries[idx]

    # Header boxes
    ax.add_patch(Rect((col_boundaries[0], 0.87), get_scaled_width(0), 0.11, fill=True, facecolor="#4A4A4A",
                      edgecolor="white", linewidth=2, transform=ax.transAxes, clip_on=False))
    ax.add_patch(Rect((col_boundaries[1], 0.87), get_scaled_width(1), 0.11, fill=True, facecolor="#4A4A4A",
                      edgecolor="white", linewidth=2, transform=ax.transAxes, clip_on=False))

    cd24_start, cd24_end = col_boundaries[2], col_boundaries[4]
    ax.add_patch(Rect((cd24_start, 0.92), cd24_end - cd24_start, 0.06, fill=True, facecolor="#4A4A4A",
                      edgecolor="white", linewidth=2, transform=ax.transAxes, clip_on=False))
    ax.add_patch(Rect((cd24_start, 0.87), cd24_end - cd24_start, 0.05, fill=True, facecolor="#6B6B6B",
                      edgecolor="white", linewidth=1, transform=ax.transAxes, clip_on=False))

    # Header text
    ax.text((col_boundaries[0] + col_boundaries[1]) / 2, 0.925, "Characteristic",
            fontsize=14, fontweight="bold", color="white", ha="center", va="center", transform=ax.transAxes)
    ax.text((col_boundaries[1] + col_boundaries[2]) / 2, 0.925, "All Patients",
            fontsize=14, fontweight="bold", color="white", ha="center", va="center", transform=ax.transAxes)
    ax.text((cd24_start + cd24_end) / 2, 0.95, "CD24 Expression",
            fontsize=14, fontweight="bold", color="white", ha="center", va="center", transform=ax.transAxes)
    ax.text((col_boundaries[2] + col_boundaries[3]) / 2, 0.895, "Low",
            fontsize=13, fontweight="bold", color="white", ha="center", va="center", transform=ax.transAxes)
    ax.text((col_boundaries[3] + col_boundaries[4]) / 2, 0.895, "High",
            fontsize=13, fontweight="bold", color="white", ha="center", va="center", transform=ax.transAxes)

    category_headers = {
        "Cancer type, n (%)", "Sex, n (%)", "Race, n (%)", "Tumor location, n (%)",
        "Stage, n (%)", "Vital status, n (%)", "Overall Survival", "Progression-Free Interval"
    }

    for i in range(len(table_rows)):
        bg_color = "#F5F5F5" if i % 2 == 0 else "white"
        for j in range(4):
            cell = table[(i, j)]
            cell.set_facecolor(bg_color)
            cell.set_text_props(va="center", fontsize=12)
            if table_rows[i][0] in category_headers and j == 0:
                cell.set_text_props(weight="bold", fontsize=13)
                cell.set_facecolor("#D9D9D9")
            if table_rows[i][0] == "N":
                cell.set_text_props(weight="bold", fontsize=13)
                cell.set_facecolor("#E8E8E8")
            if j > 0:
                cell.set_text_props(ha="center", fontsize=13)
            cell.set_edgecolor("#CCCCCC")
            cell.set_linewidth(0.5)

    plt.tight_layout()
    if SAVE_FIGURES:
        fig.savefig(fig_path, dpi=DPI, bbox_inches="tight")
    plt.close(fig)


# -----------------------------
# Master survival summary table
# -----------------------------
def build_master_survival_summary_table(
    results_cd24_os: dict,
    results_cd24_pfi: dict,
    has_pfi: bool,
) -> pd.DataFrame:
    """
    Compile a single 'master' survival summary table for all stage-stratified analyses.

    """
    rows = []

    def _to_float(x):
        if x is None:
            return np.nan
        try:
            return float(x)
        except Exception:
            s = str(x)
            m = re.search(r"[-+]?(?:\d*\.\d+|\d+)", s)
            return float(m.group(0)) if m else np.nan

    def add_cd24(results: dict, endpoint: str):
        for stage, payload in results.items():
            stats = payload.get("stats") or {}
            res = payload.get("result")

            row = {
                "analysis": "CD24",
                "stage": stage,
                "endpoint": endpoint,
                "logrank_p": _to_float(getattr(res, "p_value", np.nan)) if res is not None else np.nan,
                "Low_n": stats.get("Low", {}).get("n", np.nan),
                "High_n": stats.get("High", {}).get("n", np.nan),
                "Low_events": stats.get("Low", {}).get("events", np.nan),
                "High_events": stats.get("High", {}).get("events", np.nan),
                "HR_High_vs_Low": np.nan,
                "HR_CI_low": np.nan,
                "HR_CI_high": np.nan,
                "HR_p": np.nan,
            }

            if res is not None and hasattr(res, "hr") and res.hr is not None:
                hr_raw, ci_l_raw, ci_h_raw, p_raw = res.hr
                hr = _to_float(hr_raw)
                ci_l = _to_float(ci_l_raw)
                ci_h = _to_float(ci_h_raw)
                p_hr = _to_float(p_raw)

                if (not np.isfinite(hr)) or (hr > 50):
                    hr, ci_l, ci_h, p_hr = np.nan, np.nan, np.nan, np.nan

                row.update({"HR_High_vs_Low": hr, "HR_CI_low": ci_l, "HR_CI_high": ci_h, "HR_p": p_hr})

            rows.append(row)

    add_cd24(results_cd24_os, "OS")
    if has_pfi and results_cd24_pfi:
        add_cd24(results_cd24_pfi, "PFI")

    df_out = pd.DataFrame(rows)
    preferred = [
        "analysis", "stage", "endpoint",
        "logrank_p",
        "Low_n", "High_n", "Low_events", "High_events",
        "HR_High_vs_Low", "HR_CI_low", "HR_CI_high", "HR_p",
    ]
    cols = [c for c in preferred if c in df_out.columns] + [c for c in df_out.columns if c not in preferred]
    return df_out[cols]


# -----------------------------
# Main
# -----------------------------
def main():
    warnings.filterwarnings("ignore", category=ConvergenceWarning)
    warnings.filterwarnings("ignore", category=RuntimeWarning)

    ap = argparse.ArgumentParser(description="Generate TCGA survival figures (CD24 only).")
    ap.add_argument("--project-root", type=Path, default=None,
                    help="Path to tcga/ folder (defaults to directory containing this script).")
    ap.add_argument("--table", type=str, default="tcga_analysis_table.csv",
                    help="Filename of analysis table in results/processed/.")
    args = ap.parse_args()

    project_root = args.project_root if args.project_root is not None else Path(__file__).resolve().parent
    processed_dir = project_root / "results" / "processed"
    out_dir = project_root / "results" / "figures_tables"
    out_dir.mkdir(parents=True, exist_ok=True)

    table_path = processed_dir / args.table
    df = pd.read_csv(table_path)

    df["CD24_expr"] = pd.to_numeric(df.get("CD24_expr", np.nan), errors="coerce")
    df["time"] = pd.to_numeric(df.get("time", np.nan), errors="coerce")
    df["event"] = pd.to_numeric(df.get("event", np.nan), errors="coerce")
    df["pfi_time"] = pd.to_numeric(df.get("pfi_time", np.nan), errors="coerce")
    df["pfi_event"] = pd.to_numeric(df.get("pfi_event", np.nan), errors="coerce")

    df = df[df["stage"].isin(["I", "II", "III", "IV"])].copy()
    has_pfi = df[["pfi_time", "pfi_event"]].dropna().shape[0] > 0

    # CD24 binary for clinical table only (overall median)
    median_cd24 = df["CD24_expr"].median()
    df["CD24_binary"] = np.where(df["CD24_expr"] >= median_cd24, "High", "Low")

    stage_map = {
        "Stage I": df[df["stage"] == "I"].copy(),
        "Stage II": df[df["stage"] == "II"].copy(),
        "Stage III": df[df["stage"] == "III"].copy(),
        "Stage IV": df[df["stage"] == "IV"].copy(),
    }

    results_os = {}
    results_pfi = {}

    for stage_name, stage_df in stage_map.items():
        groups, result, sufficient, stats = analyze_cd24_stage_highlow_5yr(stage_df, stage_name, "OS")
        results_os[stage_name] = {"groups": groups, "result": result, "sufficient": sufficient, "stats": stats}

        if has_pfi:
            groups, result, sufficient, stats = analyze_cd24_stage_highlow_5yr(stage_df, stage_name, "PFI")
            results_pfi[stage_name] = {"groups": groups, "result": result, "sufficient": sufficient, "stats": stats}

    # Figure
    create_combined_os_pfi_figure(results_os, results_pfi if has_pfi else {}, out_dir / f"CD24_OS_PFI.{FIGURE_FORMAT}")

    # Master survival summary
    master = build_master_survival_summary_table(results_cd24_os=results_os, results_cd24_pfi=results_pfi, has_pfi=has_pfi)
    master_csv = out_dir / "Master_Survival_Summary.csv"
    master.to_csv(master_csv, index=False)
    print(f"[save] {master_csv}")

    # Clinical characteristics table (figure + CSV)
    build_and_save_clin_table_figure(
        df,
        out_dir / "AllPatients_ClinicalCharacteristics.png",
        out_dir / "AllPatients_ClinicalCharacteristics.csv",
    )

    print("\n✓ Saved outputs in:", out_dir)


if __name__ == "__main__":
    main()